"""initial schema

Revision ID: 7d24a924d115
Revises:
Create Date: 2026-07-15 23:35:59.166462
"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = "7d24a924d115"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "revenuecat_events",
        sa.Column("id", sa.String(length=255), nullable=False),
        sa.Column("event_type", sa.String(length=128), nullable=False),
        sa.Column("app_user_id", sa.String(length=255), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("processed_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_revenuecat_events_app_user_id"),
        "revenuecat_events",
        ["app_user_id"],
        unique=False,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("clerk_user_id", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_users_clerk_user_id"), "users", ["clerk_user_id"], unique=True
    )
    op.create_table(
        "devices",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("push_token", sa.String(length=512), nullable=False),
        sa.Column("platform", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "push_token", name="uq_device_user_token"),
    )
    op.create_index(op.f("ix_devices_user_id"), "devices", ["user_id"], unique=False)
    op.create_table(
        "listing_identifications",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("external_id", sa.String(length=128), nullable=True),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("teaser", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_listing_identifications_external_id"),
        "listing_identifications",
        ["external_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_listing_identifications_user_id"),
        "listing_identifications",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "media",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("object_key", sa.String(length=1024), nullable=False),
        sa.Column("content_type", sa.String(length=128), nullable=False),
        sa.Column("size_bytes", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("object_key"),
    )
    op.create_index(op.f("ix_media_user_id"), "media", ["user_id"], unique=False)
    op.create_table(
        "subscriptions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column(
            "plan",
            sa.Enum(
                "none", "weekly", "monthly", name="subscriptionplan", native_enum=False
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "inactive",
                "active",
                "grace_period",
                "billing_issue",
                name="subscriptionstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("product_id", sa.String(length=255), nullable=True),
        sa.Column(
            "current_period_started_at", sa.DateTime(timezone=True), nullable=True
        ),
        sa.Column("current_period_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("will_renew", sa.Boolean(), nullable=False),
        sa.Column("environment", sa.String(length=32), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id"),
    )
    op.create_table(
        "analyses",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("identification_id", sa.String(length=36), nullable=True),
        sa.Column("parent_analysis_id", sa.String(length=36), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "initial",
                "reanalysis",
                "refresh",
                name="analysiskind",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "processing",
                "completed",
                "failed",
                name="analysisstatus",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("idempotency_key", sa.String(length=255), nullable=False),
        sa.Column("request_fingerprint", sa.String(length=64), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=False),
        sa.Column("external_listing_id", sa.String(length=128), nullable=True),
        sa.Column(
            "purchase_mode",
            sa.Enum(
                "face_to_face",
                "delivery",
                "unknown",
                name="purchasemode",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("seller_contacted", sa.Boolean(), nullable=False),
        sa.Column("seller_reply_text", sa.Text(), nullable=True),
        sa.Column("seller_media", sa.JSON(), nullable=False),
        sa.Column("listing_payload", sa.JSON(), nullable=True),
        sa.Column("parent_result", sa.JSON(), nullable=True),
        sa.Column("result", sa.JSON(), nullable=True),
        sa.Column("provider_metadata", sa.JSON(), nullable=True),
        sa.Column("model_id", sa.String(length=128), nullable=True),
        sa.Column("prompt_version", sa.String(length=32), nullable=False),
        sa.Column("schema_version", sa.String(length=32), nullable=False),
        sa.Column("error_code", sa.String(length=128), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["identification_id"], ["listing_identifications.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(
            ["parent_analysis_id"], ["analyses.id"], ondelete="SET NULL"
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "user_id", "idempotency_key", name="uq_analysis_user_idempotency"
        ),
    )
    op.create_index(
        op.f("ix_analyses_created_at"), "analyses", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_analyses_external_listing_id"),
        "analyses",
        ["external_listing_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analyses_parent_analysis_id"),
        "analyses",
        ["parent_analysis_id"],
        unique=False,
    )
    op.create_index(op.f("ix_analyses_status"), "analyses", ["status"], unique=False)
    op.create_index(op.f("ix_analyses_user_id"), "analyses", ["user_id"], unique=False)
    op.create_table(
        "usage_events",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.String(length=36), nullable=False),
        sa.Column("analysis_id", sa.String(length=36), nullable=True),
        sa.Column(
            "kind",
            sa.Enum(
                "included_debit",
                "topup_credit",
                "topup_debit",
                "failure_reversal",
                "manual_adjustment",
                name="usageeventkind",
                native_enum=False,
            ),
            nullable=False,
        ),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("source_event_id", sa.String(length=255), nullable=True),
        sa.Column("period_started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("period_ends_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["analysis_id"], ["analyses.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("source_event_id"),
    )
    op.create_index(
        op.f("ix_usage_events_analysis_id"),
        "usage_events",
        ["analysis_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_usage_events_created_at"), "usage_events", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_usage_events_user_id"), "usage_events", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_usage_events_user_id"), table_name="usage_events")
    op.drop_index(op.f("ix_usage_events_created_at"), table_name="usage_events")
    op.drop_index(op.f("ix_usage_events_analysis_id"), table_name="usage_events")
    op.drop_table("usage_events")
    op.drop_index(op.f("ix_analyses_user_id"), table_name="analyses")
    op.drop_index(op.f("ix_analyses_status"), table_name="analyses")
    op.drop_index(op.f("ix_analyses_parent_analysis_id"), table_name="analyses")
    op.drop_index(op.f("ix_analyses_external_listing_id"), table_name="analyses")
    op.drop_index(op.f("ix_analyses_created_at"), table_name="analyses")
    op.drop_table("analyses")
    op.drop_table("subscriptions")
    op.drop_index(op.f("ix_media_user_id"), table_name="media")
    op.drop_table("media")
    op.drop_index(
        op.f("ix_listing_identifications_user_id"), table_name="listing_identifications"
    )
    op.drop_index(
        op.f("ix_listing_identifications_external_id"),
        table_name="listing_identifications",
    )
    op.drop_table("listing_identifications")
    op.drop_index(op.f("ix_devices_user_id"), table_name="devices")
    op.drop_table("devices")
    op.drop_index(op.f("ix_users_clerk_user_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(
        op.f("ix_revenuecat_events_app_user_id"), table_name="revenuecat_events"
    )
    op.drop_table("revenuecat_events")
    # ### end Alembic commands ###
